In [1]:
# These modules are required for loading and writing data.
from dysh.fits import GBTFITSLoad
from dysh.log import init_logging
from astropy import units as u

# These modules are used for file I/O
from dysh.util.files import dysh_data
from pathlib import Path

In [2]:
init_logging(2)

# also create a local "output" directory where temporary notebook files can be stored.
output_dir = Path.cwd() / "output"
output_dir.mkdir(exist_ok=True)

In [3]:
filename = dysh_data(test="getps")

16:05:17.790 I Resolving test=getps -> AGBT05B_047_01/AGBT05B_047_01.raw.acs/

In [4]:
sdfits = GBTFITSLoad(filename)

16:05:17.911 I Index loaded from .index file (44/93 columns). Missing columns (TCAL, WCS, calibration metadata, etc.) will be automatically loaded from FITS file when first accessed.

In [5]:
sdfits.summary()

In [6]:
tmp_dir = output_dir / "merge_sdfits"
tmp_dir.mkdir(exist_ok=True, parents=True) # Create the output directory if it does not exist.

In [7]:
sdfits.write(tmp_dir / "scan51.fits", scan=51, overwrite=True)
sdfits.write(tmp_dir / "scan52.fits", scan=52, overwrite=True)

 ID    TAG    SCAN # SELECTED
--- --------- ---- ----------
  0 8f333a945   51         44
 ID    TAG    SCAN # SELECTED
--- --------- ---- ----------
  0 ea8ec139d   52         44

In [8]:
sdfits_merged = GBTFITSLoad(tmp_dir)
sdfits_merged.files

16:05:18.447 I Loaded 2 FITS files

[PosixPath('/bigdisk/src/dysh/docs/source/users_guide/output/merge_sdfits/scan51.fits'),
 PosixPath('/bigdisk/src/dysh/docs/source/users_guide/output/merge_sdfits/scan52.fits')]

In [9]:
sdfits_merged.summary()

In [10]:
new_dir = output_dir / "merged_sdfits"
new_dir.mkdir(exist_ok=True)

In [11]:
sdfits_merged.write(new_dir / "merged_sdfits.fits", multifile=False, overwrite=True)

In [12]:
sdfits_merged = GBTFITSLoad(new_dir)
sdfits_merged.summary()

In [13]:
sdfits_merged.files

[PosixPath('/bigdisk/src/dysh/docs/source/users_guide/output/merged_sdfits/merged_sdfits.fits')]

In [14]:
sdfits.getsigref(51,52,ifnum=0,plnum=0,fdnum=0)[0].timeaverage().check_stats(0.09095205 * u.K)

16:05:22.297 I rms is OK

In [15]:

sdfits_merged.getsigref(51,52,ifnum=0,plnum=0,fdnum=0).timeaverage().check_stats(0.09095205 * u.K)

16:05:23.553 I rms is OK